### ISSUE TITLE
User control to increase/decrease simulation speed of solar system

### ISSUE THREAD

**Issue by atharvakinage** [acmpesuecc/Simul8#1]
The speed of simulation is right now at a constant rate. Implement a new feature where the user can control the speed of the simulation through arrow keys.

**Comment by SysRet8-BMS** [comment]
Please assign me this task or issue.

**Comment by lithium-anode** [comment]
Please assign this to me.

**Comment by Redslayer112** [comment]
please assign me this task @Redslayer112 -> github username

**Comment by atharvakinage** [comment]
!assign @Redslayer112 60

**Comment by SysRet8-BMS** [comment]
please assign me this task @CodeWithBhuvan -> github username

**Comment by Redslayer112** [comment]
deassign please @atharvakinage

**Comment by atharvakinage** [comment]
!deassign
