### ISSUE TITLE
Improve visual representation of the solar system

### ISSUE THREAD

**Issue by atharvakinage** [acmpesuecc/Simul8#2]
Add a nice starfield background for the solar system simulation to give it a more space like feel :D  
Also the planets and the moons are drawn as simple circles which may not be so visually appealing. Add textures or colors to represent different types of planets.

**Comment by Redslayer112** [comment]
Can I be assigned @Redslayer112 -> github username

**Comment by atharvakinage** [comment]
!assign @Redslayer112 60

**Comment by atharvakinage** [comment]
!assign @Redslayer112 60

**Comment by atharvakinage** [comment]
!assign @Redslayer112 60

**Comment by atharvakinage** [comment]
!deassign
