### ISSUE TITLE
Trail effect for the walker

### ISSUE THREAD

**Issue by atharvakinage** [acmpesuecc/Simul8#3]
Create a trail effect to visualize the path of the walker , right now pixels are drawn to track the path but make the trail fade over time to create a nice visual effect.

**Comment by lithium-anode** [comment]
Please assign this to me.

**Comment by atharvakinage** [comment]
!assign @lithium-anode 60

**Comment by lithium-anode** [comment]
Can you please reassign this to me?

**Comment by atharvakinage** [comment]
!assign @lithium-anode

**Comment by atharvakinage** [comment]
!deassign

**Comment by atharvakinage** [comment]
!assign @lithium-anode

**Comment by atharvakinage** [comment]
!deassign
