### ISSUE TITLE
Boundary collision check

### ISSUE THREAD

**Issue by atharvakinage** [acmpesuecc/Simul8#5]
It is possible that the **random walker** can move outside the bounds of the window, so implement boundary check by adding constraints to prevent the walker from going off the screen.

**Comment by SysRet8-BMS** [comment]
Can I work on this issue?

**Comment by atharvakinage** [comment]
!assign @CodeWithBhuvan

**Comment by atharvakinage** [comment]
do you still want to work on it?

**Comment by atharvakinage** [comment]
!deassign

**Comment by chandan365c** [comment]
@atharvakinage  can you assign me this?

**Comment by atharvakinage** [comment]
!assign @chandan365c

**Comment by chandan365c** [comment]
Heyy, @atharvakinage. 
 I've opened a PR... Kindly review : )

**Comment by atharvakinage** [comment]
!deassign
